### PR TITLE
[WIP] Testing mellanox CI

### PR DESCRIPTION
**Pull request by AbdYsn**

### CODE REVIEW

**Comment by mellanox-openstack** [comment]
Thanks for your PR.\n\nYou can test hw-offload configuration by commenting one of the following:\n* `/test-hw-offload`.\n `/test-all`.\n.\n\nThese commands can be run by anyone.\nThanks.

**Comment by mellanox-openstack** [comment]
Thanks for your PR.

You can test hw-offload configuration by commenting one of the following:
* `/test-hw-offload`.
 `/test-all`.
.

These commands can be run by anyone.

**Comment by mellanox-openstack** [comment]
Thanks for your PR.

You can test hw-offload configuration by commenting one of the following:
* `/test-hw-offload`.
* `/test-all`.

These commands can be run by anyone.

Thanks.

**Comment by AbdYsn** [comment]
ok to test

**Pull request closed without merging**
